spring:
  application:
    name: currency-conversion
  sleuth:
    sampler:
      probability: 1.0
  config:
    import: optional:configserver:http://localhost:8888
    
server:
  port: 8100
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka